#!/bin/bash

# move this file into venv/bin
# set the values of username/password
# change command words depending on os
# then setup_sql in the virtual environment will run these commands

echo "Setting Flask db info"

export MYSQL_DATABASE_HOST=remotemysql.com
export MYSQL_DATABASE_USER=insert plaintext username here
export MYSQL_DATABASE_PASSWORD=insert plaintext password here
export MYSQL_DATABASE_DB=insert plaintext username here
